[package]
name = "rustls-cng"
version = "0.7.0-dev"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "Windows CNG API bridge for rustls"
license = "MIT/Apache-2.0"
repository = "https://github.com/rustls/rustls-cng"
documentation = "https://docs.rs/rustls-cng"
readme = "README.md"
keywords = ["cng", "tls", "rustls", "windows"]
edition = "2024"
publish = false

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
no-default-features = true

[dependencies]
rustls = { git = "https://github.com/rustls/rustls.git", default-features = false, features = ["std"] }
rustls-pki-types = "1"
time = { version = "0.3.43", default-features = false, optional = true }
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security_Cryptography"] }

[dev-dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
rustls-pki-types = "1"

[features]
default = ["log", "aws-lc-rs"]
aws-lc-rs = ["rustls/aws-lc-rs"]
fips = ["rustls/fips"]
log = ["rustls/log"]
ring = ["rustls/ring"]
time = ["dep:time"]
brotli = ["rustls/brotli"]
zlib = ["rustls/zlib"]
