[package]
name = "rustls-cng"
version = "0.8.0-dev"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "Windows CNG API bridge for rustls"
license = "MIT/Apache-2.0"
repository = "https://github.com/rustls/rustls-cng"
documentation = "https://docs.rs/rustls-cng"
readme = "README.md"
keywords = ["cng", "tls", "rustls", "windows"]
edition = "2024"
publish = false

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
no-default-features = true
features = ["time"]

[dependencies]
rustls = { git = "https://github.com/rustls/rustls.git", default-features = false }
time = { version = "0.3", default-features = false, optional = true }
bitflags = "2"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security_Cryptography"] }

[dev-dependencies]
rustls-aws-lc-rs = { git = "https://github.com/rustls/rustls.git" }
rustls-util = { git = "https://github.com/rustls/rustls.git" }
rustls-native-certs = "0.8"

[features]
default = ["rustls-tracing", "rustls-webpki"]
time = ["dep:time"]
rustls-webpki= ["rustls/webpki"]
rustls-tracing = ["rustls/tracing"]
rustls-brotli = ["rustls/brotli"]
rustls-zlib = ["rustls/zlib"]
